# Generated by Django 5.0.3 on 2024-03-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.SmallIntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('no_of_guests', models.SmallIntegerField()),
                ('bookingDate', models.DateTimeField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.SmallIntegerField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.SmallIntegerField(max_length=5)),
            ],
        ),
    ]
